version: "2"
services:
  baseimage:
    build: ./image/baseimage
    image: coal/baseimage

# mariadb:
#   build: ./image/mysql
#   image: coal/mysql
#   depends_on:
#     - baseimage
#   networks:
#     database:
#       aliases:
#         - database
#   ports:
#     - "3306:3306"
#   volumes:
#     #- ./conf/mysql/my.cnf:/etc/mysql/my.cnf
#     - database:/var/lib/mysql

  nginx:
    build: ./image/nginx
    image: coal/nginx
    depends_on:
      - baseimage
      - php5
    networks:
      - web
    ports:
      - "80:80"
    volumes:
      - ../:/www/coal
      - ./conf/nginx/servers.d:/etc/nginx/servers.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf

  php5:
    build: ./image/php5
    image: coal/php5
    depends_on:
      - baseimage
    networks:
      database:
        aliases:
          - php
      web:
        aliases:
          - php
    ports:
      - "9000:9000"
    volumes:
      - ../:/www/coal
      #- ./conf/php5/php.ini:/etc/php5/php.ini
      - ./conf/php5/fpm/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
      - ./conf/php5/fpm/pool.d:/etc/php5/fpm/pool.d

volumes:
  database:

networks:
  database:
  web:
